import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { Header, Footer, Hero } from "lib/ui";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" display="grid">
        <Header position="fixed" zIndex="banner" />
        <Hero />
        <Footer />
      </Box>
    </>
  );
}
