import Head from "next/head";
import { x } from "@xstyled/emotion";
import { Button, useColorMode } from "@chakra-ui/react";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <x.main>
        <x.h1 color="orange.400">Welcome to the index.tsx page!</x.h1>
        <Button onClick={toggleColorMode}>
          Toggle {colorMode === "light" ? "Dark" : "Light"}
        </Button>
      </x.main>
    </>
  );
}
